version: '3.7'
services:
  app:
    build: .
    container_name: uniflow_app
    hostname: uniflow_app
    ports:
      - 8080:80
    links:
      - db
  db:
    image: mysql
    container_name: uniflow_db
    hostname: uniflow_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
