parameters:

    # Services Class
    dw.user.class:                   Darkwood\UserBundle\Services\UserService

    # Entities Class
    dw.entity.user.class:            Darkwood\UserBundle\Entity\User

    dw.user.authentication.handler.success.class: Darkwood\UserBundle\Security\LoginSuccessHandler

services:

    Darkwood\UserBundle\Security\LoginFailureHandler:
        arguments: ['@router', '@security.csrf.token_manager']
        tags:
            - { name: monolog.logger, channel: security }

    Darkwood\UserBundle\Security\LoginSuccessHandler:
        arguments: ['@router', '@security.authorization_checker']
        tags:
            - { name: monolog.logger, channel: security }

    Darkwood\UserBundle\Services\UserService:
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ addRepository,    [ userRepository,  Darkwood\UserBundle\Entity\User ] ]
            - [ addService,       [ userManager, '@fos_user.user_manager'  ] ]

    Darkwood\UserBundle\Form\Type\ProfileFormType:
        tags:
            - { name: form.type, alias: darkwood_user_profile }

    Darkwood\UserBundle\Form\Type\RegistrationFormType:
        tags:
            - { name: form.type, alias: darkwood_user_registration }

    wd.user.provider.fos_userbundle_bridge:
        class: Darkwood\UserBundle\Security\Core\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - {facebook: facebookId}
