_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

front:
    resource: '@FrontBundle/Resources/config/routing.yml'
    prefix:   /
