# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                failure_handler: Darkwood\UserBundle\Security\LoginFailureHandler
                success_handler: Darkwood\UserBundle\Security\LoginSuccessHandler
            oauth:
                resource_owners:
                    facebook:      '/login/check-facebook'
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: wd.user.provider.fos_userbundle_bridge
            logout:       true
            anonymous:    true
            remember_me:
                secret:   acPuzffj787lJbsr
                lifetime: 3600
                path:     /
                domain:   ~

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: ROLE_USER, host: 'uniflow.darkwood.fr' }
        - { path: ^/, role: ROLE_USER }
