parameters:
    dw.doctrineCache.class: Cache\Bridge\DoctrineCacheBridge

services:

    _defaults:
        autowire: true
        autoconfigure: true
        #public: false

    dw.defaultCache:
        class: '%dw.doctrineCache.class%'
        arguments: [ '@cache.provider.defaultCache' ]

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.string_loader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }
