remove_trailing_slash:
  path: /{url}
  defaults: { _controller: FrontBundle:Common:removeTrailingSlash }
  requirements:
    url: .*/$
  methods: [GET]

component_sftp_read:
  path:   /read
  defaults: { _controller: FrontBundle:Components/SFTPComponent:read }
