remove_trailing_slash:
  path: /{url}
  defaults: { _controller: FrontBundle:Common:removeTrailingSlash }
  requirements:
    url: .*/$
  methods: [GET]

home:
  locales:  { fr: '/', en: '/en', de: '/de' }
  defaults: { _controller: FrontBundle:Default:home }
