remove_trailing_slash:
  path: /{url}
  defaults: { _controller: FrontBundle:Common:removeTrailingSlash }
  requirements:
    url: .*/$
  methods: [GET]

component_sftp:
  resource: '@FrontBundle/Resources/config/routing/components/sftp.yml'
  prefix:   /component/sftp

history:
  resource: '@FrontBundle/Resources/config/routing/history.yml'
  prefix:   /history

home:
  path: /
  defaults: { _controller: FrontBundle:Default:home }
