remove_trailing_slash:
    path: /{url}
    defaults: { _controller: FrontBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

home:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
