parameters:
    # Components Class
    dw.component.sftp.class: Darkwood\FrontBundle\Components\SFTPComponent

    # Services Class
    dw.tag.class:                       Darkwood\FrontBundle\Services\TagService
    dw.history.class:                   Darkwood\FrontBundle\Services\HistoryService

    # Entities Class
    dw.entity.tag.class:                Darkwood\FrontBundle\Entity\Tag
    dw.entity.history.class:            Darkwood\FrontBundle\Entity\History

    # Transformers Class
    dw.form.history.class:           Darkwood\FrontBundle\Form\HistoryType

services:
    dw.component.sftp:
        class: "%dw.component.sftp.class%"
        
    dw.tag:
        class: "%dw.tag.class%"
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
            - [ addRepository, [ tagRepository, "%dw.entity.tag.class%" ] ]
            
    dw.history:
        class: "%dw.history.class%"
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
            - [ addRepository, [ historyRepository, "%dw.entity.history.class%" ] ]

    dw.form.history:
        class: "%dw.form.history.class%"
        arguments: ["@dw.tag"]
        tags:
            - { name: form.type }